# fly.toml app configuration file generated for waktool-prod on 2023-06-26T02:06:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "waktool-prod"
primary_region = "cdg"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1

[services.concurrency]
type = "requests"
hard_limit = 99999
soft_limit = 99999
