server:
  address: 0.0.0.0
  port: ${APP_PORT:8000}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15435/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:changeme}

oauth2:
  discord:
    token-uri: https://discord.com/api/oauth2/token
    user-info-uri: https://discord.com/api/users/@me
    authorization-grant-type: authorization_code
    client-id: ${CLIENT_ID:changeme}
    client-secret: ${CLIENT_SECRET:changeme}
    scope: identify,email
    redirect-uri: ${BASE_URL:changeme}/api/oauth/discord/redirect

jwt:
  secret: ${JWT_SECRET:changeme}

waktool:
  base-url: ${FRONT_URL:changeme}
  resources-path: ${RESOURCES_PATH:file:front/dist/}
